### PR TITLE
Escape all control characters

### PR DESCRIPTION
**Pull request by laanwj**
All control characters (U+0000..U+001f) should be escaped according to RFC4627. Update gen accordingly.

Also escape `U+007f DELETE` - is not mentioned in RFC4627 as a control character, but it is helpful to escape it as many fonts don't render it, or weirdly.

Adds a basic roundtrip test to check escaping.

### CODE REVIEW

**Comment by laanwj** [comment]
Just found out that it was already attempted to handle this through `isprint` - however this function is locale dependent, this had the correct outptut in US locale. Updated to make the `write` locale independent.

**Comment by laanwj** [comment]
Ping @jgarzik

**Comment by jonasschnelli** [comment]
ACK

**Comment by MarcoFalke** [comment]
Nit fixed in  7482163

**Pull request merged**
