### PR TITLE
Some code cleanups

### PR DESCRIPTION
**Pull request by jonasschnelli**
* [cleancode] use lowerCamelCase for all methods
* replace global function find_value() with UniValue::findValue()

not sure about the `getBool()` / `isTrue()` change.

### CODE REVIEW

**Comment by jgarzik** [comment]
* Agree on localCamelCase change, as discussed in IRC
* Global function find_value is slated for removal; would prefer to not touch this at all, leaving it as deprecated legacy.

**Comment by MarcoFalke** [comment]
@jonasschnelli are you still working on this?

**Comment by jonasschnelli** [comment]
Not really. I like the PR, but it would be a wide API break. Not sure about it.

**Comment by MarcoFalke** [comment]
So you'd need to slowly deprecate public methods... Not sure if it's worth the effort.

**Pull request closed without merging**
