### PR TITLE
Build fixups

### PR DESCRIPTION
**Pull request by theuni**
A few fixups:
- Non-recursive build
- Use glibtoolize where necessary
- Move generated/copied files to build-aux
- Use silent build rools
- Don't require gnu-style files

### CODE REVIEW

**Comment by theuni** [comment]
@jonasschnelli What was your concern about include paths?

**Comment by jonasschnelli** [comment]
@theuni: Is it not common to place the exposed headers in `/include`?

**Comment by jonasschnelli** [comment]
Nice!
ACK

**Comment by theuni** [comment]
@jonasschnelli yes. That allows you to (for ex) build test programs that use the headers the same way a real downstream would.

I'll do another PR for that after this one's merged to avoid piling on.

**Comment by jgarzik** [comment]
ACK.  Waiting on Travis.

**Pull request merged**
