### PR TITLE
Support parsing raw literals in UniValue

### PR DESCRIPTION
**Pull request by ryanofsky**
Fixes following test failures in https://github.com/nst/JSONTestSuite

bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_negative_real.json
bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_string.json
bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_false.json
bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_null.json
bitcoin SHOULD_HAVE_PASSED  y_string_space.json
bitcoin SHOULD_HAVE_PASSED  y_structure_string_empty.json
bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_int.json
bitcoin SHOULD_HAVE_PASSED  y_structure_lonely_true.json

### CODE REVIEW

**Comment by ryanofsky** [comment]
@laanwj also mentioned this change would be useful to have in bitcoin: https://github.com/bitcoin/bitcoin/issues/9028#issuecomment-257885368

**Comment by laanwj** [comment]
Yes, this would be useful, we work around this with an ugly hack right now.

**Comment by MarcoFalke** [comment]
@ryanofsky Make sure to add those to the  `Makefile.am` as well.

**Comment by ryanofsky** [comment]
Thanks, updated Makefile.am.

**Comment by jgarzik** [comment]
This PR, take by itself, introduces an unterminated-string bug at the core of the parser.

Usefully, the next PR - #32 - fixes this bug.

In the future, we want to avoid this split-submission, as it impacts git bisect.

**Comment by ryanofsky** [comment]
I think the opposite is true: The merge of #32 was bad and introduced an unterminated string bug, while this pr, AFAICT is fine. I posted a fix for the current unterminated string bug in #36.

**Pull request merged**
