### PR TITLE
Detect non-minimal UTF-8 decoding

### PR DESCRIPTION
**Pull request by ryanofsky**
Fixes following test failures in https://github.com/nst/JSONTestSuite

bitcoin SHOULD_HAVE_FAILED  n_string_overlong_sequence_2_bytes.json

### CODE REVIEW

**Comment by MarcoFalke** [comment]
@ryanofsky Needs rebase if still relevant.

**Comment by ryanofsky** [comment]
Thanks, rebased 745f66748e5d569565a0e9f8b4ac04da93b98b88 -> 36911dd952dc00259221317bc1c81d61296890dd ([mininal-utf8.0](https://github.com/ryanofsky/univalue/commits/pr/mininal-utf8.0) -> [mininal-utf8.1](https://github.com/ryanofsky/univalue/commits/pr/mininal-utf8.1))

**Comment by ryanofsky** [comment]
Rebased again to fix conflicts 36911dd952dc00259221317bc1c81d61296890dd -> 4224a1f1456fa46f85635915d14327407294d97a ([mininal-utf8.1](https://github.com/ryanofsky/univalue/commits/pr/mininal-utf8.1) -> [mininal-utf8.2](https://github.com/ryanofsky/univalue/commits/pr/mininal-utf8.2))

**Comment by jgarzik** [comment]
This seems to fail the well known robustness principle, "be liberal in what you accept"  https://en.wikipedia.org/wiki/Robustness_principle

Is there a reason why non-minimal UTF8 input should trigger a failure?

**Comment by ryanofsky** [comment]
Not sure. Maybe it would be good to raise the issue with the https://github.com/nst/JSONTestSuite test project.

FWIW, python seems to reject this utf8 encoding:

```
>>> b"\xc0\xaf".decode("utf8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

**Comment by ryanofsky** [comment]
Looked into this some more. On the question of whether this is valid UTF-8, I think the answer is that it is unambiguously invalid. From https://tools.ietf.org/html/rfc3629:

```
   Implementations of the decoding algorithm above MUST protect against
   decoding invalid sequences.  For instance, a naive implementation may
   decode the overlong UTF-8 sequence C0 80 into the character U+0000,
   or the surrogate pair ED A1 8C ED BE B4 into U+233B4.  Decoding
   invalid sequences may have security consequences or cause other
   problems.  See Security Considerations (Section 10) below.
```

On the other hand, the article describing the test suite at http://seriot.ch/parsing_json.php says "The parsing of invalid UTF-8 will be implementation defined" and the failing test was changed to have an "i_" (implementation-defined) prefix instead of an "n_" failing prefix here:

- https://github.com/nst/JSONTestSuite/issues/30
- https://github.com/nst/JSONTestSuite/commit/d4f056c42b42451deefbeb88b1684d34088b4476
- https://github.com/nst/JSONTestSuite/blob/master/test_parsing/i_string_overlong_sequence_2_bytes.json

On the other other hand though, https://github.com/nst/JSONTestSuite/issues/30 seems to suggest that JSON implementations that accept invalid UTF-8 input are need to replace it with U+FFFD, which isn't something this implementation is doing.

**Comment by jgarzik** [comment]
Thanks for the additional research and info.  The main question is whether the input is *invalid* or merely *not optimal*.   The answer to that question should dictate univalue's behavior upon that input.

"unambiguously invalid" would therefore imply an ACK here - will review further to confirm

**Comment by daira** [comment]
Well, [chapter 3 of the Unicode Standard](https://www.unicode.org/versions/Unicode13.0.0/ch03.pdf) is pretty clear that this is nonconformant to that standard:
image

**Pull request closed without merging**
