### PR TITLE
Handle UTF-8

### LINKED ISSUE #16: UTF-8 not handled while writing
UTF-8 is not handled while writing strings in `json_escape`. The result of this is that unicode sequences like '\u1234' will be expanded to their UTF-8 equivalent on a roundtrip, and re-encoded as multiple unicode characters `\u00XX\u00XX...` which is not correct.

This could be handled:

If the input/output is UTF-8 encoded, UTF-8 sequences in strings can be passed through on output without any processing (according to RFC 4627 "All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).")

From RFC 4627:
```
JSON text SHALL be encoded in Unicode.  The default encoding is
UTF-8.
```

### PR DESCRIPTION
**Pull request by laanwj**
This adds full UTF-8 support both on input and output.

Input: read and validate full UTF-8, both Basic Multilingual Plane and extended characters.
Collate surrogate pairs as specified in RFC4627.
This ensures that UTF-8 strings that reach the application are always valid, and that invalid UTF-8 fails parsing.

Output: Assume UTF-8 strings provided for output are valid.
The escaping was broken, fix this by not encoding UTF-8 characters with \u.
Writing them to the output stream as-is is the right thing to do.
See https://www.ietf.org/rfc/rfc4627.txt:

    "JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8."

Also add tests for the new functionality.
Fixes #16.
Sister PR in the bitcoin core repository, with examples: [Add full UTF-8 support to RPC #7892](https://github.com/bitcoin/bitcoin/pull/7892)

### CODE REVIEW

**Comment by MarcoFalke** [comment]
You didn't adjust `src/univalue/Makefile.am`?

**Comment by laanwj** [comment]
Ah yes, thanks for noticing, this needs the build system changes
Op 18 apr. 2016 21:11 schreef "MarcoFalke" <notifications@github.com>:

You didn't adjust src/univalue/Makefile.am?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jgarzik/univalue/pull/22#issuecomment-211535259>

**Comment by MarcoFalke** [comment]
Concept ACK

**Comment by luke-jr** [comment]
This seems fairly well-tested in Core. Would be nice to have it in an official release of the lib too...

**Comment by MarcoFalke** [comment]
@jgarzik Anything holding this back?

**Pull request merged**
