### PR TITLE
Add git ignores for build artifacts

### PR DESCRIPTION
**Pull request by jmcorgan**
Some stray files produced by autogen/configure/make show up as uncommitted files, this ignores them.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Nice.
How about adding one .gitignore file on root level?

**Comment by jmcorgan** [comment]
Well, I'm not familiar enough with the tree to know the proper ones, and you already had them split out by dir.  Up to you.

**Comment by jonasschnelli** [comment]
I would prefer updating https://github.com/jgarzik/univalue/blob/master/.gitignore (maybe have a look at https://github.com/bitcoin/bitcoin/blob/master/.gitignore).
Less files, more centralized git configuration.

**Comment by jgarzik** [comment]
typically IME,
* if it is duplicated, put it at the top level
* otherwise local

**Comment by jmcorgan** [comment]
Updated per jgarzik's guidlines

**Pull request merged**
